### ISSUE TITLE
Thank you for your project

### ISSUE THREAD

**Issue by ZengLeiPro** [nanoninja/docker-nginx-php-mysql#1]
If I want to use it in production, how should I modify it?

**Comment by nanoninja** [comment]
Hi @ZengLeiPro 

Thanks for your support.

It depends, what do you want to change? I added a cautionary message not to use it in production, because I have not yet measured all the security aspects. I created this environment for a practical purpose.

I notice that this environment has a little unexpected success and I would like to have more feedback and also ideas to improve it.

**Comment by chasgames** [comment]
@nanoninja 

This project is awesome, thank you very much

**Comment by ghostal** [comment]
+1 on the thanks here, too.

I came across an issue installing the composer dependencies, where `apigen` won't install, but it looks like this in an issue with the dependencies for `apigen/apigen` itself, not this project, so filed [an issue](https://github.com/ApiGen/ApiGen/issues/1000) there instead. Thought I would mention it here though, in case someone else was having a similar issue.

**Comment by nanoninja** [comment]
@ghostal Thanks for your feedback, I'll fix that.

**Comment by nanoninja** [comment]
@ghostal I temporarily [fixed](https://github.com/nanoninja/docker-nginx-php-mysql/commit/58613a90e364d899f1c293e98792b5ced4093340) the error

The [build](https://travis-ci.org/nanoninja/docker-nginx-php-mysql) is passed.
