### ISSUE TITLE
Unable to get SSL

### ISSUE THREAD

**Issue by qweluke** [nanoninja/docker-nginx-php-mysql#5]
> ERR_SSL_SERVER_CERT_BAD_FORMAT

I have cloned your repo, next I run command to generate [certificate](https://github.com/nanoninja/docker-nginx-php-mysql#configure-nginx-with-ssl-certificates) but when I try to visit my page via ssl i'm still getting:

>This site can’t provide a secure connection
> mysite.dev doesn't adhere to security standards.
> ERR_SSL_SERVER_CERT_BAD_FORMAT

**Comment by nanoninja** [comment]
Hi @qweluke,

Thanks, I got the same error. Let me fix that

**Comment by qweluke** [comment]
@nanoninja That's from my second attempt (mysite.dev).
I've just cloned your repo, followed the instructions and now having this:
https://i.imgur.com/AYdQe46.png

Please focus on "Not secure" part, not nginx warnings

**Comment by nanoninja** [comment]
@qweluke 

Ok I see.

This is normal but nothing to worry about because it is a [self-signed certificate](http://www.inmotionhosting.com/support/website/ssl/self-signed-ssl-certificate-warning).
I will improve the application so that it can work with a domain name without too much configuration.

If you use the make gen-certs command by default, the domain "localhost" used to generate the certificate.

**Comment by nanoninja** [comment]
@qweluke 

In the next version there will be the possibility to configure the [server name](https://github.com/nanoninja/docker-nginx-php-mysql/blob/dev/.env).

It already works but I do some verification.

**Comment by qweluke** [comment]
@nanoninja great! Thank you!
